<a href="https://colab.research.google.com/github/lsuhpchelp/loniscworkshop2023/blob/main/day2/IntermediatePython_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Day 4: Scientific Computing with Python (Exercises)
## 5th LBRN-LONI Scientific Computing Bootcamp
May 26 2023

In [ ]:
# Run this first so that you do not have to load NumPy every time
import numpy as np

## **1. Warm Up**

### 1) Creation:

Create a 1-D array:

* Type is `float32`
* From `0` to no more than `30`, step length is `3`
* Do not use `np.array()` method!
* Desired output:
> ```
[ 0.  3.  6.  9. 12. 15. 18. 21. 24. 27.]
float32
```

In [ ]:
myAry = # FIX ME
print(myAry)
print(myAry.dtype)

### 2) Reshape

* Reshape the above 1-D array to a 2-D array with 2 rows
* Desired output:
> ```
[[ 0.  3.  6.  9. 12.]
 [15. 18. 21. 24. 27.]]
 ```

In [ ]:
myAry2 = # FIX ME
print(myAry2)

### 3) Slicing

* Pick every other element on axis 1, and keep axis 0
* Desired output:

> ```
[[ 0.  6. 12.]
 [15. 21. 27.]]
 ```

In [ ]:
myAry3 = # FIX ME
print(myAry3)

### 4) Basic Operations

* Calculate the square of each element, then change the data type to `int`
* Desired output:
> ```
[[  0  36 144]
 [225 441 729]]
 ```

In [ ]:
myAry4 = # FIX ME
print(myAry4)

### 5) Aggregation Functions

* Sum over rows and columns of above array, respectively
* Desired output:
> ```
[225 477 873]
[ 180 1395]
```

In [ ]:
row_sum = # FIX ME
print(row_sum)

col_sum = # FIX ME
print(col_sum)

### 6) Broadcast

* Calculate the radius from Cartesian coordinates
* Raius of coordinates `(x, y)` is the square root of `x^2 + y^2` (Hint: Use `np.sqrt()`)
* Both `x` and `y` range from `-3` to `3`, a total of linearlly spaced `7` elements 
* You result should be a `(7 x 7)` array, each element is the radius of coordinates `(x, y)`.
* Desired output:
> ```
x =  [-3. -2. -1.  0.  1.  2.  3.]
y = 
 [[-3.]
 [-2.]
 [-1.]
 [ 0.]
 [ 1.]
 [ 2.]
 [ 3.]]
r = 
 [[4.24 3.61 3.16 3.   3.16 3.61 4.24]
 [3.61 2.83 2.24 2.   2.24 2.83 3.61]
 [3.16 2.24 1.41 1.   1.41 2.24 3.16]
 [3.   2.   1.   0.   1.   2.   3.  ]
 [3.16 2.24 1.41 1.   1.41 2.24 3.16]
 [3.61 2.83 2.24 2.   2.24 2.83 3.61]
 [4.24 3.61 3.16 3.   3.16 3.61 4.24]]
 ```

In [ ]:
x = # FIX ME
y = # FIX ME
print("x = ", x)
print("y = \n", y)

r = # FIX ME
print("r = \n", r.round(decimals=2))

## **2. Write Your Own ReLU Function**

> * The purpose of this exercise is to practice the use of advanced indexing.

Rectified Linear Unit (ReLU) is a commonly used activation function in machine learning. The definition is simple:

![P_2_ReLU.png](https://github.com/lsuhpchelp/loniscworkshop2023/raw/main/day2/images/P_2_ReLU.png)

Here, you are asked to write your own ReLU funcion:

* Input: An array of numbers (int or float).
* Output: An array of the same shape as the input, but replace all negative values to 0.

**!!CAUTION!!**

* I did not say the input is 1-D array. Could be any arbitrary shape.
* Use ufunc, advanced indexing or any other method for efficiency.
* Do **NOT** use loop even if you are attempted to!! Don't do anything like this:
> ```
for i in range(x.size):
    if x[i]<0:
      ...
```
* Hint: Boolean value `True` is `1`, and `False` is `0` when used as integers.

In [ ]:
# Define your own ReLU function
def relu(x):
  # FIX ME

myAry = np.random.random([5, 5]) - 0.5
print("Input = \n", myAry)
print("\nOutput = \n", relu(myAry))

## **3. Statistics with NumPy**

> * The purpose of this exercise is to practice the use of slicing, aggregation functions and advanced indexing.

Here, you are asked to perform some basic statistical calculation on the data array previously loaded from "data.txt". The loaded data should have 3 columns:
> ```
Index, Brain Weight, Body Weight
```

**!!CAUTION!!**

* Use aggregation functions, advanced indexing or any other method for efficiency.
* Do **NOT** use loop even if you are attempted to!!

In [ ]:
# Load data

txtfile = 'https://github.com/lsuhpchelp/loniscworkshop2023/raw/main/day2/data.txt'
data = np.loadtxt(txtfile, 
                  skiprows=16, 
                  usecols={0,1,2}, 
                  comments="#")
print("Loaded data:\n", data)

### 1) Calculate the average, max, and min brain weight and body weight, respectively

Complete the below calculations.

In [ ]:
# Calculate average, max, and min brain weight
ave_brain_weight = # FIX ME
max_brain_weight = # FIX ME
min_brain_weight = # FIX ME
print("Average brain weight is:\t", ave_brain_weight)
print("Max brain weight is:\t", max_brain_weight)
print("Min brain weight is:\t", min_brain_weight)

# Calculate average, max, and min body weight
ave_body_weight = # FIX ME
max_body_weight = # FIX ME
min_body_weight = # FIX ME
print("Average brain weight is:\t", ave_body_weight)
print("Max brain weight is:\t", max_body_weight)
print("Min brain weight is:\t", min_body_weight)

### 2) Filter out bad data points

Now, notice there is a bad point: Someone's brain is heavier than the body! That is physically impossible. Please remove any rows where the brain is heavier than the body, and redo above calculation.

Hint: Use advanced indexing.

In [ ]:
# Filter out bad data points
data_filtered = # FIX ME
print("Filtered data:\n", data_filtered)

# Calculate average, max, and min brain weight
ave_brain_weight = # FIX ME
max_brain_weight = # FIX ME
min_brain_weight = # FIX ME
print("Average brain weight is:\t", ave_brain_weight)
print("Max brain weight is:\t", max_brain_weight)
print("Min brain weight is:\t", min_brain_weight)

# Calculate average, max, and min body weight
ave_body_weight = # FIX ME
max_body_weight = # FIX ME
min_body_weight = # FIX ME
print("Average brain weight is:\t", ave_body_weight)
print("Max brain weight is:\t", max_body_weight)
print("Min brain weight is:\t", min_body_weight)

## **4. Wave Function Propagation of 1-D Harmonic Oscillator**

> * The purpose of this exercise it to practice various NumPy array creationg methods, ufuncs, and aggregation functions in a close-to-practical problem.
> * Don't worry if you do not work in physics! You can still finish the exercise even if you do not know the physics.

1-D harmonic oscillator is one of the most fundamental dynamic systems in both classical and quantime-mechanical physics. It describes the dynamics of a particle inside a square potential `V(x) ∝ x^2`. In classical picture, it is just a mass attached to a spring oscillating back and forth. In quantum-mechanical picture, however, is a little more complicated.

In quantum mechanics, particle is not found in a defined place, instead it has a probability distribution of where it may appear in space, which is defined by **wave function**. In a quantum-mechanical picture, it looks more like a wave packet, but the packet oscillates back and forth collectively just like the mass in the classical picture.

![P_4_scenario.png](https://github.com/lsuhpchelp/loniscworkshop2023/raw/main/day2/images/P_4_scenario.png)


Here, you are asked to write a simple code to study how the wave function of a 1-D harmonic oscillator propagates using quantum mechanical methods.

**!!CAUTION!!**

* Use aggregation functions, ufuncs or any other method for efficiency.
* Do **NOT** use loop even if you are attempted to!!

### 1) Create the initial wave function on a discrete grid

First create a 1-D array of `x` coordinates from `[-L/2, L/2]` (`L=10.`), evenly spaced in `101` grid points. You will also need to find out step length `dx`.

Then create the initial wave function on the above grid, which should look like:

![P_4_psi.png](https://github.com/lsuhpchelp/loniscworkshop2023/raw/main/day2/images/P_4_psi.png)

The `√N` is the normalization factor.

In [ ]:
# Define parameters
N = 101       # Number of grid points
L = 10.0      # Length of the box

# Define the array x coordinates and obtrain step length dx
x, dx = # FIX ME

# Calculate the initial wave function
# For simplicity, first calculate without dividing by normalization factor "√N", then do the normalization
# Hint: You may need np.exp(), np.sqrt(), sum()
psi = # FIX ME
psi /= # FIX ME

# Plot probability distribution abs(psi)**2
import matplotlib.pyplot as plt
plt.plot(x, np.abs(psi)**2, label="Wave function")
plt.legend()
plt.show()

### 2) Create the Hamiltonian matrix

The Hamiltonian matrix is core of the dynamics in quantume mechanics. The Hamiltonian matrix is an `(N, N)` matrix (NumPy array), which can be defined this way:

![P_4_H.png](https://github.com/lsuhpchelp/loniscworkshop2023/raw/main/day2/images/P_4_H.png)

Basically, matrix `T` (kinetic energy) is a tridiagonal matrix, with all diagonal elements being `-2` and off-diagonal elements being `1`, then times a constant `-1/dx^2`. Matrix `V` (potential energy) is a diagonal matrix, with each element is `V(x)=x^2/2` at the corresponding coordinate. All other unwritten elements are `0`.

In [ ]:
# Create matrix T
# Hint: You may need np.diag(). Do not forget argument "k" to set off diagonal elements.
T = # FIX ME

# Create matrix V
# Hint: You may need np.diag()
V = # FIX ME

# Create Hamiltonian matrix H
H = T + V

# Print Hamiltonian matrix
print(H)

### 3) Build the propagator

Now we are getting to the good stuff! By doing this, you can proudly tell your friends that you did some actual physics! Based on the Hamiltonian matrix, we will now build the propagator, which is a matrix you actually multiple to the left of the wave function. The propagator is defined like this:

![P_4_CN.png](https://github.com/lsuhpchelp/loniscworkshop2023/raw/main/day2/images/P_4_CN.png)

Where `I` is the `(N, N)` identity matrix, `i` is the imaginary unit, and `dt` is the time step. Notice that there is a matrix inverse!

> This method is called Crank-Nicholson method, the most commonly used numerical method to propagate wave function. The reason we form the propagator this way is to preserve normalization of the wave function.

In [ ]:
# Define time step length (This needs to be small enough for propagator the be near identity)
T = 4*np.pi
nt = 20000
t, dt = np.linspace(0, T, nt, retstep=True)
print("Time step length is:", dt)

# Create the propagator
# Hint: You may need:
#       np.linalg.inv() : Matrix inverse 
#       np.dot()        : Matrix multiplication
#       1j              : Imaginary unit
U = # FIX ME

# Print the propagator
print("Propagator is:\n", U)

# Look, your propagator should be close to identity matrix

### 4) Let's see the results!

Now let's see the results! This part is not very related to NumPy, so I will not ask you to write or understand. But if you have done correctly in previous steps, just run this part and you should see a nice animation of wave packet oscillating back and forth like a classical particle. If it is messed up, check previous steps again.

In [ ]:
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation

# Change psi to complex number
psi = psi.astype("complex")

# Create a figure and axes
fig, ax = plt.subplots()

# Set the x and y axis of the plot
ax.set_xlim(-L/2, L/2)
ax.set_ylim(0, 1)

# Initialize an empty line object
ax.plot(x, x**2/20, "--")
line, = ax.plot([], [])

# Define the animation update function
nframe = 100
def update(frame):

    # Generate y values based on the frame number
    global psi
    global nframe
    for index in range(int(nt/nframe)):
      psi = np.dot(U, psi)

    # Update the line data
    line.set_data(x, np.abs(psi)**2)

    return line,

# Create the animation
animation = FuncAnimation(fig, update, frames=nframe, interval=50, blit=True)

#animation.save("P_4_result.gif")
from IPython.display import HTML
HTML(animation.to_jshtml())

If you are doing it correctly, you should get something like this:
![P_4_result.gif](https://github.com/lsuhpchelp/loniscworkshop2023/raw/main/day2/images/P_4_result.gif)

Now, congratulations! You just did some physics research! 

FYI, what you just did is actually solving the most fundamental equation in quantum mechanics: **Time-Dependent Schrodinger's Equation** (**TDSE**). TDSE governs the quantum-mechanical dynamics of the microscopic particles. In actual research, physicists usually propagate TDSE like this to see how wave function evolve in time to extract useful information. And TDSE results are sometimes regarded as the **exact** retults, pretty much equivalent to what you would get in experiments. 

But actual research problems could be much more costly. They may need larger grid, 3-D instead of 1-D, spherical coordinates, multiple particles, different physics models, etc..